# Generated by Django 6.0.5 on 2026-05-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_state', models.CharField(blank=True, max_length=100)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
