# Generated by Django 6.0.5 on 2026-05-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='hostel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hostelimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='hostelimage',
            name='image_type',
            field=models.CharField(blank=True, choices=[('entrance', 'Entrance'), ('dorm_room', 'Dorm Room'), ('common_area', 'Common Area'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='hostelimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
