# Generated by Django 6.0.6 on 2026-06-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0003_hostel_category_hostel_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
