# Generated by Django 6.0.6 on 2026-06-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image_post_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bumped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='room_type',
            field=models.CharField(blank=True, choices=[('bed', 'Bed in a shared room'), ('room', 'Private room'), ('apartment', 'Apartment'), ('other', 'Other')], max_length=20),
        ),
    ]
