# Generated by Django 6.0.5 on 2026-05-07 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amenities', '0001_initial'),
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelamenity',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostels.hostel'),
        ),
    ]
