# Generated by Django 6.0.5 on 2026-05-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramsession',
            name='last_interaction',
        ),
        migrations.AddField(
            model_name='telegramsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='telegramsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
