# Generated by Django 6.0.5 on 2026-05-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField()),
                ('report_data', models.JSONField(default=dict)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
